### ISSUE TITLE
実装するDBテーブルを考える

### ISSUE THREAD

**Issue by Kuya0307** [morijyobi/python_flask_web_final_exercise_2023-Kuya0307#4]
- [ ] 患者情報テーブル
- [ ] 予約テーブル
- [ ] 中間テーブル
- [ ] 症状テーブル

**Comment by Kuya0307** [comment]
図書管理システムに変更したためクローズ

**Comment by hosokawa3217** [comment]
確認しました。 
**私のほうで病院の予約システムに関するissueを削除することができますが、いかがでしょうか。**
その場合は、削除したいissueのissue番号(例.#6)をおしらせください。

**Comment by Kuya0307** [comment]
ぜひお願いしたいです。
こちらissue番号です。
#1
<https://github.com/morijyobi/python_flask_web_final_exercise_2023-Kuya0307/issues/1>
,#2
<https://github.com/morijyobi/python_flask_web_final_exercise_2023-Kuya0307/issues/2>
,#3
<https://github.com/morijyobi/python_flask_web_final_exercise_2023-Kuya0307/issues/3>
,#4
<https://github.com/morijyobi/python_flask_web_final_exercise_2023-Kuya0307/issues/4>
,#6
<https://github.com/morijyobi/python_flask_web_final_exercise_2023-Kuya0307/issues/6>

2023年6月26日(月) 8:17 hosokawa Junya ***@***.***>:
